-- Seed 168+ Verified Resistance Movements
INSERT INTO exercises (id, name, muscle_group, secondary_muscles, modality, tier, mechanic, equipment) VALUES
  ('chest_wall_push_up', 'Wall Push-Up', 'Chest', ARRAY['Triceps', 'Anterior Deltoid']::TEXT[], 'Calisthenics', 'Beginner', 'Push', 'Bodyweight'),
  ('chest_incline_push_up', 'Incline Push-Up', 'Chest', ARRAY['Triceps', 'Anterior Deltoid', 'Core']::TEXT[], 'Calisthenics', 'Beginner', 'Push', 'Bodyweight'),
  ('chest_knee_push_up', 'Knee Push-Up', 'Chest', ARRAY['Triceps', 'Anterior Deltoid']::TEXT[], 'Calisthenics', 'Beginner', 'Push', 'Bodyweight'),
  ('chest_standard_push_up', 'Standard Push-Up', 'Chest', ARRAY['Triceps', 'Anterior Deltoid', 'Core']::TEXT[], 'Calisthenics', 'Intermediate', 'Push', 'Bodyweight'),
  ('chest_wide_grip_push_up', 'Wide-Grip Push-Up', 'Chest', ARRAY['Anterior Deltoid', 'Triceps']::TEXT[], 'Calisthenics', 'Intermediate', 'Push', 'Bodyweight'),
  ('chest_hand_release_push_up', 'Hand-Release Push-Up', 'Chest', ARRAY['Triceps', 'Anterior Deltoid', 'Upper Back']::TEXT[], 'Calisthenics', 'Intermediate', 'Push', 'Bodyweight'),
  ('chest_archer_push_up', 'Archer Push-Up', 'Chest', ARRAY['Triceps', 'Anterior Deltoid', 'Core']::TEXT[], 'Calisthenics', 'Intermediate', 'Push', 'Bodyweight'),
  ('chest_spiderman_push_up', 'Spiderman Push-Up', 'Chest', ARRAY['Triceps', 'Obliques', 'Hip Flexors']::TEXT[], 'Calisthenics', 'Intermediate', 'Push', 'Bodyweight'),
  ('chest_assisted_one_arm_push_up', 'Assisted One-Arm Push-Up', 'Chest', ARRAY['Triceps', 'Core', 'Anterior Deltoid']::TEXT[], 'Calisthenics', 'Advanced', 'Push', 'Bodyweight'),
  ('chest_full_one_arm_push_up', 'Full One-Arm Push-Up', 'Chest', ARRAY['Triceps', 'Core', 'Anterior Deltoid']::TEXT[], 'Calisthenics', 'Advanced', 'Push', 'Bodyweight'),
  ('chest_hindu_push_up', 'Hindu Push-Up', 'Chest', ARRAY['Triceps', 'Deltoids', 'Spine Erectors', 'Hamstrings']::TEXT[], 'Calisthenics', 'Advanced', 'Push / Flow', 'Bodyweight'),
  ('chest_belt_reach_push_up', 'Belt-Reach Push-Up', 'Chest', ARRAY['Triceps', 'Obliques', 'Core']::TEXT[], 'Calisthenics', 'Advanced', 'Push / Reach', 'Kettlebell'),
  ('chest_clapping_push_up', 'Clapping Push-Up', 'Chest', ARRAY['Triceps', 'Anterior Deltoid']::TEXT[], 'Calisthenics', 'Explosive', 'Plyometric Push', 'Bodyweight'),
  ('chest_knee_slap_push_up', 'Knee-Slap Push-Up', 'Chest', ARRAY['Triceps', 'Core', 'Hip Flexors']::TEXT[], 'Calisthenics', 'Explosive', 'Plyometric Push', 'Bodyweight'),
  ('chest_aztec_push_up', 'Aztec Push-Up', 'Chest', ARRAY['Triceps', 'Core', 'Hip Flexors']::TEXT[], 'Calisthenics', 'Explosive', 'Plyometric Push', 'Bodyweight'),
  ('chest_flying_superman_push_up', 'Flying Superman Push-Up', 'Chest', ARRAY['Triceps', 'Shoulders', 'Core', 'Posterior Chain']::TEXT[], 'Calisthenics', 'Explosive', 'Plyometric Push', 'Bodyweight'),
  ('chest_dips', 'Chest Dips', 'Chest', ARRAY['Triceps', 'Anterior Deltoid']::TEXT[], 'Calisthenics', 'Intermediate', 'Push', 'Parallel Bars'),
  ('chest_flat_bb_bench_press', 'Flat Barbell Bench Press', 'Chest', ARRAY['Triceps', 'Anterior Deltoid']::TEXT[], 'Free Weights', 'Intermediate', 'Push', 'Barbell'),
  ('chest_incline_bb_bench_press', 'Incline Barbell Bench Press', 'Chest', ARRAY['Clavicular Pectoral', 'Anterior Deltoid', 'Triceps']::TEXT[], 'Free Weights', 'Intermediate', 'Push', 'Barbell'),
  ('chest_incline_db_bench_press', 'Incline Dumbbell Bench Press', 'Chest', ARRAY['Clavicular Pectoral', 'Anterior Deltoid', 'Triceps']::TEXT[], 'Free Weights', 'Intermediate', 'Push', 'Dumbbells'),
  ('chest_db_floor_press', 'Dumbbell Floor Press', 'Chest', ARRAY['Triceps', 'Anterior Deltoid']::TEXT[], 'Free Weights', 'Intermediate', 'Push', 'Dumbbells'),
  ('chest_kb_floor_press', 'Kettlebell Floor Press', 'Chest', ARRAY['Triceps', 'Anterior Deltoid', 'Forearms']::TEXT[], 'Free Weights', 'Intermediate', 'Push', 'Kettlebell'),
  ('chest_flat_db_flyes', 'Flat Dumbbell Flyes', 'Chest', ARRAY['Anterior Deltoid']::TEXT[], 'Free Weights', 'Intermediate', 'Isolation / Fly', 'Dumbbells'),
  ('chest_incline_db_flyes', 'Incline Dumbbell Flyes', 'Chest', ARRAY['Clavicular Pectoral', 'Anterior Deltoid']::TEXT[], 'Free Weights', 'Intermediate', 'Isolation / Fly', 'Dumbbells'),
  ('chest_standing_upward_chest_fly', 'Standing Upward Chest Fly', 'Chest', ARRAY['Anterior Deltoid', 'Core']::TEXT[], 'Free Weights', 'Intermediate', 'Isolation / Fly', 'Dumbbells'),
  ('chest_db_pullover', 'Dumbbell Pullover', 'Chest', ARRAY['Latissimus Dorsi', 'Triceps Long Head', 'Serratus Anterior']::TEXT[], 'Free Weights', 'Intermediate', 'Pull / Push', 'Dumbbell'),
  ('chest_cable_pec_fly_high_low', 'Cable Pec Fly (High-to-Low)', 'Chest', ARRAY['Lower Pectoral', 'Anterior Deltoid']::TEXT[], 'Cables & Machines', 'Intermediate', 'Isolation / Fly', 'Cable Machine'),
  ('chest_incline_cable_crossover', 'Incline Cable Crossover (Low-to-High)', 'Chest', ARRAY['Clavicular Pectoral', 'Anterior Deltoid']::TEXT[], 'Cables & Machines', 'Intermediate', 'Isolation / Fly', 'Cable Machine'),
  ('chest_machine_chest_press', 'Machine Chest Press', 'Chest', ARRAY['Triceps', 'Anterior Deltoid']::TEXT[], 'Cables & Machines', 'Beginner', 'Push', 'Machine'),
  ('chest_pec_deck', 'Pec Deck (Butterfly Machine)', 'Chest', ARRAY['Anterior Deltoid']::TEXT[], 'Cables & Machines', 'Beginner', 'Isolation / Fly', 'Machine'),
  ('back_doorway_row', 'Doorway Row', 'Back', ARRAY['Biceps', 'Rhomboids', 'Rear Deltoid']::TEXT[], 'Calisthenics', 'Beginner', 'Pull', 'Bodyweight'),
  ('back_inverted_row', 'Inverted Row (Feet on floor)', 'Back', ARRAY['Biceps', 'Rhomboids', 'Latissimus Dorsi', 'Core']::TEXT[], 'Calisthenics', 'Beginner', 'Pull', 'Bar / Suspension Trainer'),
  ('back_feet_elevated_inverted_row', 'Feet-Elevated Inverted Row', 'Back', ARRAY['Biceps', 'Rhomboids', 'Latissimus Dorsi', 'Core']::TEXT[], 'Calisthenics', 'Intermediate', 'Pull', 'Bar / Box'),
  ('back_one_arm_inverted_row', 'One-Arm Inverted Row', 'Back', ARRAY['Biceps', 'Latissimus Dorsi', 'Core', 'Grip']::TEXT[], 'Calisthenics', 'Advanced', 'Pull', 'Bar / Suspension Trainer'),
  ('back_band_assisted_pull_up', 'Band-Assisted Pull-Up', 'Back', ARRAY['Biceps', 'Latissimus Dorsi', 'Rear Deltoid']::TEXT[], 'Calisthenics', 'Beginner', 'Pull', 'Pull-Up Bar / Resistance Band'),
  ('back_eccentric_chin_up', 'Eccentric Chin-Up', 'Back', ARRAY['Biceps', 'Latissimus Dorsi', 'Forearms']::TEXT[], 'Calisthenics', 'Beginner', 'Pull / Negative', 'Pull-Up Bar'),
  ('back_standard_pull_up', 'Standard Pull-Up', 'Back', ARRAY['Latissimus Dorsi', 'Rhomboids', 'Biceps', 'Forearms']::TEXT[], 'Calisthenics', 'Intermediate', 'Pull', 'Pull-Up Bar'),
  ('back_standard_chin_up', 'Standard Chin-Up', 'Back', ARRAY['Biceps', 'Latissimus Dorsi', 'Forearms']::TEXT[], 'Calisthenics', 'Intermediate', 'Pull', 'Pull-Up Bar'),
  ('back_side_to_side_pull_up', 'Side-to-Side Pull-Up', 'Back', ARRAY['Latissimus Dorsi', 'Biceps', 'Core']::TEXT[], 'Calisthenics', 'Intermediate', 'Pull', 'Pull-Up Bar'),
  ('back_ring_row', 'Gymnastic Ring / Suspension Row', 'Back', ARRAY['Biceps', 'Rhomboids', 'Rear Deltoid', 'Core']::TEXT[], 'Calisthenics', 'Intermediate', 'Pull', 'Gymnastic Rings'),
  ('back_front_lever', 'Front Lever', 'Back', ARRAY['Latissimus Dorsi', 'Core', 'Rear Deltoid', 'Forearms']::TEXT[], 'Calisthenics', 'Advanced', 'Static Hold', 'Pull-Up Bar / Rings'),
  ('back_back_lever', 'Back Lever', 'Back', ARRAY['Biceps', 'Pectorals', 'Lower Back', 'Rear Deltoid']::TEXT[], 'Calisthenics', 'Advanced', 'Static Hold', 'Pull-Up Bar / Rings'),
  ('back_bodyweight_renegade_row', 'Bodyweight Renegade Row', 'Back', ARRAY['Core', 'Obliques', 'Biceps']::TEXT[], 'Calisthenics', 'Intermediate', 'Pull / Anti-Rotation', 'Bodyweight'),
  ('back_bb_deadlift', 'Conventional Barbell Deadlift', 'Back', ARRAY['Hamstrings', 'Glutes', 'Erector Spinae', 'Trapezius', 'Forearms']::TEXT[], 'Free Weights', 'Intermediate', 'Hinge / Pull', 'Barbell'),
  ('back_bb_bent_over_row', 'Barbell Bent-Over Row', 'Back', ARRAY['Latissimus Dorsi', 'Rhomboids', 'Trapezius', 'Biceps', 'Erector Spinae']::TEXT[], 'Free Weights', 'Intermediate', 'Pull', 'Barbell'),
  ('back_pendlay_row', 'Pendlay Row', 'Back', ARRAY['Latissimus Dorsi', 'Rhomboids', 'Erector Spinae', 'Trapezius']::TEXT[], 'Free Weights', 'Advanced', 'Explosive Pull', 'Barbell'),
  ('back_single_arm_db_row', 'Single-Arm Dumbbell Row', 'Back', ARRAY['Latissimus Dorsi', 'Rhomboids', 'Biceps', 'Rear Deltoid']::TEXT[], 'Free Weights', 'Intermediate', 'Pull', 'Dumbbell'),
  ('back_db_renegade_row', 'Dumbbell Renegade Row', 'Back', ARRAY['Core', 'Obliques', 'Latissimus Dorsi', 'Triceps']::TEXT[], 'Free Weights', 'Advanced', 'Pull / Anti-Rotation', 'Dumbbells'),
  ('back_kb_renegade_row', 'Kettlebell Renegade Row', 'Back', ARRAY['Core', 'Obliques', 'Latissimus Dorsi', 'Forearms']::TEXT[], 'Free Weights', 'Advanced', 'Pull / Anti-Rotation', 'Kettlebells'),
  ('back_kb_360_clean', 'Kettlebell 360 Clean', 'Back', ARRAY['Latissimus Dorsi', 'Obliques', 'Trapezius', 'Forearms']::TEXT[], 'Free Weights', 'Intermediate', 'Rotational Pull', 'Kettlebell'),
  ('back_explosive_kb_row', 'Explosive Kettlebell Row (Hand-to-Hand)', 'Back', ARRAY['Latissimus Dorsi', 'Core', 'Biceps', 'Grip']::TEXT[], 'Free Weights', 'Explosive', 'Dynamic Pull', 'Kettlebell'),
  ('back_t_bar_row', 'Chest-Supported T-Bar Row', 'Back', ARRAY['Latissimus Dorsi', 'Rhomboids', 'Trapezius', 'Rear Deltoid']::TEXT[], 'Free Weights', 'Intermediate', 'Pull', 'T-Bar Machine / Barbell'),
  ('back_lat_pulldown', 'Lat Pulldown', 'Back', ARRAY['Latissimus Dorsi', 'Biceps', 'Rear Deltoid']::TEXT[], 'Cables & Machines', 'Beginner', 'Pull', 'Cable Machine'),
  ('back_seated_cable_row', 'Seated Cable Row', 'Back', ARRAY['Latissimus Dorsi', 'Rhomboids', 'Biceps', 'Trapezius']::TEXT[], 'Cables & Machines', 'Beginner', 'Pull', 'Cable Machine'),
  ('back_straight_arm_cable_pulldown', 'Straight-Arm Cable Pulldown', 'Back', ARRAY['Latissimus Dorsi', 'Teres Major', 'Triceps Long Head']::TEXT[], 'Cables & Machines', 'Intermediate', 'Isolation Pull', 'Cable Machine'),
  ('back_face_pulls', 'Face Pulls', 'Back', ARRAY['Rear Deltoid', 'Rhomboids', 'External Rotators', 'Trapezius']::TEXT[], 'Cables & Machines', 'Beginner', 'Pull / Rotation', 'Cable Machine'),
  ('sh_floor_pike_push_up', 'Floor Pike Push-Up', 'Shoulders', ARRAY['Triceps', 'Upper Chest', 'Serratus Anterior']::TEXT[], 'Calisthenics', 'Beginner', 'Push', 'Bodyweight'),
  ('sh_feet_elevated_pike_push_up', 'Feet-Elevated Pike Push-Up', 'Shoulders', ARRAY['Triceps', 'Anterior Deltoid', 'Core']::TEXT[], 'Calisthenics', 'Intermediate', 'Push', 'Box / Bench'),
  ('sh_push_backs', 'Push-Backs', 'Shoulders', ARRAY['Triceps', 'Core', 'Latissimus Dorsi']::TEXT[], 'Calisthenics', 'Intermediate', 'Push', 'Bodyweight'),
  ('sh_wall_handstand_push_up', 'Wall Handstand Push-Up', 'Shoulders', ARRAY['Triceps', 'Upper Trapezius', 'Core']::TEXT[], 'Calisthenics', 'Advanced', 'Push', 'Wall'),
  ('sh_freestanding_handstand_push_up', 'Freestanding Handstand Push-Up', 'Shoulders', ARRAY['Triceps', 'Trapezius', 'Core', 'Forearms']::TEXT[], 'Calisthenics', 'Advanced', 'Push / Balance', 'Bodyweight'),
  ('sh_standing_bb_ohp', 'Standing Overhead Barbell Press (OHP)', 'Shoulders', ARRAY['Triceps', 'Upper Chest', 'Core', 'Trapezius']::TEXT[], 'Free Weights', 'Intermediate', 'Push', 'Barbell'),
  ('sh_seated_db_press', 'Seated Overhead Dumbbell Press', 'Shoulders', ARRAY['Triceps', 'Upper Trapezius']::TEXT[], 'Free Weights', 'Intermediate', 'Push', 'Dumbbells'),
  ('sh_seated_arnold_press', 'Seated Arnold Press', 'Shoulders', ARRAY['Anterior Deltoid', 'Lateral Deltoid', 'Triceps']::TEXT[], 'Free Weights', 'Intermediate', 'Push / Rotation', 'Dumbbells'),
  ('sh_push_press', 'Push Press', 'Shoulders', ARRAY['Triceps', 'Quadriceps', 'Glutes', 'Core']::TEXT[], 'Free Weights', 'Intermediate', 'Explosive Push', 'Barbell / Dumbbells'),
  ('sh_bottoms_up_kb_press', 'Bottoms-Up Kettlebell Overhead Press', 'Shoulders', ARRAY['Rotator Cuff', 'Forearms', 'Core', 'Triceps']::TEXT[], 'Free Weights', 'Advanced', 'Push / Stability', 'Kettlebell'),
  ('sh_kb_halo', 'Kettlebell Halo', 'Shoulders', ARRAY['Rotator Cuff', 'Trapezius', 'Core']::TEXT[], 'Free Weights', 'Beginner', 'Mobility / Rotation', 'Kettlebell'),
  ('sh_across_body_chops', 'Across-the-Body Diagonal Chop', 'Shoulders', ARRAY['Obliques', 'Core', 'Anterior Deltoid']::TEXT[], 'Free Weights', 'Intermediate', 'Rotational Lift', 'Dumbbell / Kettlebell'),
  ('sh_db_lateral_raise', 'Dumbbell Lateral Raise', 'Shoulders', ARRAY['Lateral Deltoid', 'Upper Trapezius']::TEXT[], 'Free Weights', 'Intermediate', 'Isolation', 'Dumbbells'),
  ('sh_seated_db_reverse_fly', 'Seated Dumbbell Reverse Fly', 'Shoulders', ARRAY['Rear Deltoid', 'Rhomboids', 'Trapezius']::TEXT[], 'Free Weights', 'Intermediate', 'Isolation', 'Dumbbells'),
  ('sh_front_plate_raise', 'Front Plate Raise', 'Shoulders', ARRAY['Anterior Deltoid', 'Trapezius']::TEXT[], 'Free Weights', 'Beginner', 'Isolation', 'Weight Plate'),
  ('sh_kb_windmill', 'Kettlebell Windmill', 'Shoulders', ARRAY['Obliques', 'Hamstrings', 'Glutes', 'Core']::TEXT[], 'Free Weights', 'Advanced', 'Hinge / Overhead Stability', 'Kettlebell'),
  ('sh_kb_mill', 'Kettlebell Mill', 'Shoulders', ARRAY['Rotator Cuff', 'Trapezius', 'Core', 'Forearms']::TEXT[], 'Free Weights', 'Advanced', 'Rotational Swing', 'Kettlebell / Clubbell'),
  ('sh_cable_lateral_raise', 'Cable Lateral Raise', 'Shoulders', ARRAY['Lateral Deltoid']::TEXT[], 'Cables & Machines', 'Intermediate', 'Isolation', 'Cable Machine'),
  ('sh_reverse_pec_deck', 'Reverse Pec Deck Fly', 'Shoulders', ARRAY['Rear Deltoid', 'Rhomboids']::TEXT[], 'Cables & Machines', 'Beginner', 'Isolation', 'Machine'),
  ('sh_machine_overhead_press', 'Machine Overhead Shoulder Press', 'Shoulders', ARRAY['Triceps', 'Anterior Deltoid']::TEXT[], 'Cables & Machines', 'Beginner', 'Push', 'Machine'),
  ('arm_ring_bicep_curls', 'Gymnastic Ring Curls / Inverted Curls', 'Biceps', ARRAY['Brachialis', 'Forearms', 'Core']::TEXT[], 'Calisthenics', 'Intermediate', 'Pull / Curl', 'Gymnastic Rings'),
  ('arm_bb_curl', 'Standing Barbell Curl', 'Biceps', ARRAY['Brachialis', 'Forearms']::TEXT[], 'Free Weights', 'Beginner', 'Isolation / Curl', 'Barbell'),
  ('arm_ez_bar_preacher_curl', 'EZ-Bar Preacher Curl', 'Biceps', ARRAY['Brachialis', 'Brachioradialis']::TEXT[], 'Free Weights', 'Intermediate', 'Isolation / Curl', 'EZ-Bar / Preacher Bench'),
  ('arm_db_curl', 'Standing Alternating Dumbbell Curl', 'Biceps', ARRAY['Brachialis', 'Forearms']::TEXT[], 'Free Weights', 'Beginner', 'Isolation / Curl', 'Dumbbells'),
  ('arm_incline_db_curl', 'Incline Dumbbell Curl', 'Biceps', ARRAY['Long Head Biceps', 'Forearms']::TEXT[], 'Free Weights', 'Intermediate', 'Isolation / Curl', 'Dumbbells / Incline Bench'),
  ('arm_hammer_curl', 'Dumbbell Hammer Curl', 'Biceps', ARRAY['Brachialis', 'Brachioradialis']::TEXT[], 'Free Weights', 'Beginner', 'Isolation / Curl', 'Dumbbells'),
  ('arm_one_arm_concentration_curl', 'One-Arm Concentration Curl', 'Biceps', ARRAY['Short Head Biceps', 'Brachialis']::TEXT[], 'Free Weights', 'Intermediate', 'Isolation / Curl', 'Dumbbell'),
  ('arm_kb_reverse_curl', 'Kettlebell Reverse Curl (Motorcycle Wrist)', 'Biceps', ARRAY['Brachioradialis', 'Wrist Extensors']::TEXT[], 'Free Weights', 'Intermediate', 'Isolation / Curl', 'Kettlebell'),
  ('arm_cable_bicep_curl', 'Standing Cable Bicep Curl', 'Biceps', ARRAY['Brachialis', 'Forearms']::TEXT[], 'Cables & Machines', 'Beginner', 'Isolation / Curl', 'Cable Machine'),
  ('arm_diamond_push_up', 'Diamond Push-Up', 'Triceps', ARRAY['Inner Chest', 'Anterior Deltoid', 'Core']::TEXT[], 'Calisthenics', 'Intermediate', 'Push', 'Bodyweight'),
  ('arm_bench_dips', 'Bench Dips', 'Triceps', ARRAY['Anterior Deltoid', 'Chest']::TEXT[], 'Calisthenics', 'Beginner', 'Push', 'Bench / Chair'),
  ('arm_ring_triceps_extension', 'Gymnastic Ring Triceps Extension', 'Triceps', ARRAY['Core', 'Serratus Anterior']::TEXT[], 'Calisthenics', 'Advanced', 'Isolation / Extension', 'Gymnastic Rings'),
  ('arm_close_grip_bench_press', 'Close-Grip Barbell Bench Press', 'Triceps', ARRAY['Pectorals', 'Anterior Deltoid']::TEXT[], 'Free Weights', 'Intermediate', 'Push', 'Barbell'),
  ('arm_lying_skullcrusher_db_kb', 'Lying Skullcrusher (DB / KB)', 'Triceps', ARRAY['Triceps Long Head', 'Forearms']::TEXT[], 'Free Weights', 'Intermediate', 'Isolation / Extension', 'Dumbbells / Kettlebell'),
  ('arm_standing_overhead_tricep_ext', 'Standing Overhead Tricep Extension', 'Triceps', ARRAY['Triceps Long Head', 'Core']::TEXT[], 'Free Weights', 'Intermediate', 'Isolation / Extension', 'Dumbbell / Kettlebell'),
  ('arm_cable_rope_pushdown', 'Triceps Rope Pushdown', 'Triceps', ARRAY['Lateral Head Triceps']::TEXT[], 'Cables & Machines', 'Beginner', 'Isolation / Extension', 'Cable Machine'),
  ('core_forearm_plank', 'Forearm Plank (Standard / Bear / Feet-Elevated)', 'Core', ARRAY['Transverse Abdominis', 'Glutes', 'Shoulders']::TEXT[], 'Calisthenics', 'Beginner', 'Isometric Anti-Extension', 'Bodyweight'),
  ('core_rkc_plank', 'RKC Plank', 'Core', ARRAY['Rectus Abdominis', 'Glutes', 'Quadriceps', 'Lats']::TEXT[], 'Calisthenics', 'Advanced', 'Max-Tension Isometric', 'Bodyweight'),
  ('core_side_plank', 'Side Plank', 'Core', ARRAY['Obliques', 'Gluteus Medius', 'Quadratus Lumborum']::TEXT[], 'Calisthenics', 'Intermediate', 'Isometric Anti-Lateral Flexion', 'Bodyweight'),
  ('core_dragon_flag', 'Dragon Flag', 'Core', ARRAY['Rectus Abdominis', 'Hip Flexors', 'Lats', 'Lower Back']::TEXT[], 'Calisthenics', 'Advanced', 'Anti-Extension / Leverage', 'Bench / Sturdy Post'),
  ('core_l_sit', 'L-Sit', 'Core', ARRAY['Rectus Abdominis', 'Hip Flexors', 'Triceps', 'Quads']::TEXT[], 'Calisthenics', 'Advanced', 'Isometric Compression', 'Floor / Parallettes'),
  ('core_human_flag', 'Human Flag', 'Core', ARRAY['Obliques', 'Lats', 'Deltoids', 'Forearms']::TEXT[], 'Calisthenics', 'Advanced', 'Isometric Lateral Lever', 'Vertical Pole'),
  ('core_dead_bug', 'Dead Bug', 'Core', ARRAY['Transverse Abdominis', 'Pelvic Floor', 'Hip Flexors']::TEXT[], 'Calisthenics', 'Beginner', 'Anti-Extension', 'Bodyweight'),
  ('core_bird_dog', 'Bird Dog', 'Core', ARRAY['Erector Spinae', 'Glutes', 'Deltoids']::TEXT[], 'Calisthenics', 'Beginner', 'Cross-Body Stability', 'Bodyweight'),
  ('core_superman_hold', 'Superman Hold', 'Core', ARRAY['Erector Spinae', 'Glutes', 'Hamstrings']::TEXT[], 'Calisthenics', 'Beginner', 'Spinal Extension', 'Bodyweight'),
  ('core_kb_straight_arm_hold', 'Static Straight-Arm Kettlebell Hold', 'Core', ARRAY['Rotator Cuff', 'Deltoids', 'Obliques']::TEXT[], 'Free Weights', 'Intermediate', 'Isometric Stability', 'Kettlebell'),
  ('core_ab_wheel_rollout', 'Ab Wheel Rollout', 'Core', ARRAY['Rectus Abdominis', 'Lats', 'Posterior Chain']::TEXT[], 'Calisthenics', 'Advanced', 'Anti-Extension', 'Ab Wheel'),
  ('core_hanging_knee_raise', 'Hanging Knee Raise', 'Core', ARRAY['Hip Flexors', 'Forearms / Grip']::TEXT[], 'Calisthenics', 'Beginner', 'Dynamic Flexion', 'Pull-Up Bar'),
  ('core_alt_straight_leg_raise', 'Alternating Straight-Leg Hanging Raise', 'Core', ARRAY['Rectus Abdominis', 'Hip Flexors', 'Forearms']::TEXT[], 'Calisthenics', 'Intermediate', 'Dynamic Flexion', 'Pull-Up Bar'),
  ('core_toes_to_bar', 'Toes-to-Bar', 'Core', ARRAY['Rectus Abdominis', 'Lats', 'Hip Flexors', 'Grip']::TEXT[], 'Calisthenics', 'Advanced', 'Dynamic Flexion', 'Pull-Up Bar'),
  ('core_oblique_hanging_leg_raise', 'Oblique Hanging Leg Raise', 'Core', ARRAY['Obliques', 'Hip Flexors', 'Grip']::TEXT[], 'Calisthenics', 'Advanced', 'Rotational Flexion', 'Pull-Up Bar'),
  ('core_sit_up_twisting', 'Sit-Up / Twisting Sit-Up', 'Core', ARRAY['Obliques', 'Hip Flexors']::TEXT[], 'Calisthenics', 'Beginner', 'Dynamic Flexion / Rotation', 'Bodyweight'),
  ('core_crunches_reverse_side', 'Floor Crunches (Standard, Reverse, Side)', 'Core', ARRAY['Rectus Abdominis', 'Obliques']::TEXT[], 'Calisthenics', 'Beginner', 'Dynamic Flexion', 'Bodyweight'),
  ('core_v_ups', 'V-Ups', 'Core', ARRAY['Rectus Abdominis', 'Hip Flexors']::TEXT[], 'Calisthenics', 'Intermediate', 'Dynamic Flexion', 'Bodyweight'),
  ('core_flutter_bicycle_kicks', 'Flutter Kicks / Bicycle Kicks', 'Core', ARRAY['Lower Abdominals', 'Hip Flexors', 'Obliques']::TEXT[], 'Calisthenics', 'Beginner', 'Dynamic Flexion / Rotation', 'Bodyweight'),
  ('core_russian_twist', 'Russian Twist', 'Core', ARRAY['Obliques', 'Rectus Abdominis']::TEXT[], 'Free Weights', 'Intermediate', 'Rotational', 'Bodyweight / Dumbbell'),
  ('core_cable_woodchopper', 'Cable Woodchoppers (High-to-Low / Low-to-High)', 'Core', ARRAY['Obliques', 'Shoulders', 'Hips']::TEXT[], 'Cables & Machines', 'Intermediate', 'Rotational', 'Cable Machine'),
  ('core_windshield_wipers', 'Hanging Windshield Wipers', 'Core', ARRAY['Obliques', 'Lats', 'Forearms']::TEXT[], 'Calisthenics', 'Advanced', 'Rotational Leverage', 'Pull-Up Bar'),
  ('core_cable_crunch', 'Cable Crunch (Kneeling)', 'Core', ARRAY['Rectus Abdominis']::TEXT[], 'Cables & Machines', 'Beginner', 'Loaded Flexion', 'Cable Machine'),
  ('leg_air_squat', 'Bodyweight Air Squat', 'Legs', ARRAY['Quadriceps', 'Glutes', 'Hamstrings', 'Calves']::TEXT[], 'Calisthenics', 'Beginner', 'Squat', 'Bodyweight'),
  ('leg_sissy_squat', 'Sissy Squat', 'Legs', ARRAY['Quadriceps / Rectus Femoris', 'Knee Connective Tissue', 'Core']::TEXT[], 'Calisthenics', 'Advanced', 'Isolation Knee Extension', 'Bodyweight'),
  ('leg_bb_back_squat', 'Barbell Back Squat', 'Legs', ARRAY['Quadriceps', 'Glutes', 'Hamstrings', 'Erector Spinae']::TEXT[], 'Free Weights', 'Intermediate', 'Squat', 'Barbell'),
  ('leg_bb_front_squat', 'Barbell Front Squat', 'Legs', ARRAY['Quadriceps', 'Upper Back', 'Core', 'Glutes']::TEXT[], 'Free Weights', 'Advanced', 'Squat', 'Barbell'),
  ('leg_goblet_squat', 'Goblet Squat', 'Legs', ARRAY['Quadriceps', 'Glutes', 'Core', 'Upper Back']::TEXT[], 'Free Weights', 'Beginner', 'Squat', 'Dumbbell / Kettlebell'),
  ('leg_step_up', 'Step-Up', 'Legs', ARRAY['Quadriceps', 'Glutes', 'Calves']::TEXT[], 'Calisthenics', 'Beginner', 'Unilateral Squat', 'Box / Bench'),
  ('leg_single_leg_box_squat', 'Single-Leg Box Squat', 'Legs', ARRAY['Quadriceps', 'Glutes', 'Balance Stabilizers']::TEXT[], 'Calisthenics', 'Intermediate', 'Unilateral Squat', 'Box / Bench'),
  ('leg_bulgarian_split_squat', 'Bulgarian Split Squat', 'Legs', ARRAY['Quadriceps', 'Glutes', 'Hip Flexors', 'Hamstrings']::TEXT[], 'Free Weights', 'Intermediate', 'Unilateral Squat', 'Bench / Dumbbells'),
  ('leg_pistol_squat', 'Pistol Squat (Assisted or Full)', 'Legs', ARRAY['Quadriceps', 'Glutes', 'Ankle Stabilizers', 'Core']::TEXT[], 'Calisthenics', 'Advanced', 'Unilateral Squat', 'Bodyweight'),
  ('leg_shrimp_squat', 'Shrimp Squat', 'Legs', ARRAY['Quadriceps', 'Glutes', 'Balance Stabilizers']::TEXT[], 'Calisthenics', 'Advanced', 'Unilateral Squat', 'Bodyweight'),
  ('leg_skater_squat', 'Skater Squat', 'Legs', ARRAY['Quadriceps', 'Glutes', 'Hamstrings']::TEXT[], 'Calisthenics', 'Intermediate', 'Unilateral Squat', 'Bodyweight'),
  ('leg_jump_squat', 'Jump Squat', 'Legs', ARRAY['Quadriceps', 'Glutes', 'Calves']::TEXT[], 'Calisthenics', 'Explosive', 'Plyometric Squat', 'Bodyweight'),
  ('leg_hack_squat_leg_press', 'Hack Squat / Leg Press Machine', 'Legs', ARRAY['Quadriceps', 'Glutes']::TEXT[], 'Cables & Machines', 'Beginner', 'Push', 'Machine'),
  ('leg_extension_machine', 'Leg Extension Machine', 'Legs', ARRAY['Quadriceps']::TEXT[], 'Cables & Machines', 'Beginner', 'Isolation Knee Extension', 'Machine'),
  ('leg_rdl_bb_db_kb', 'Romanian Deadlift (Barbell / Dumbbell / Single-Leg)', 'Legs', ARRAY['Hamstrings', 'Glutes', 'Erector Spinae']::TEXT[], 'Free Weights', 'Intermediate', 'Hinge', 'Barbell / Dumbbells'),
  ('leg_suitcase_deadlift', 'Suitcase Deadlift', 'Legs', ARRAY['Glutes', 'Hamstrings', 'Obliques / Anti-Lateral Flexion']::TEXT[], 'Free Weights', 'Intermediate', 'Hinge / Asymmetric', 'Kettlebell / Dumbbell'),
  ('leg_kb_good_morning', 'Kettlebell Good Morning', 'Legs', ARRAY['Hamstrings', 'Glutes', 'Erector Spinae']::TEXT[], 'Free Weights', 'Intermediate', 'Hinge', 'Kettlebell'),
  ('leg_glute_bridge_hip_thrust', 'Glute Bridge / Barbell Hip Thrust', 'Legs', ARRAY['Gluteus Maximus', 'Hamstrings', 'Adductors']::TEXT[], 'Free Weights', 'Intermediate', 'Hip Extension', 'Bodyweight / Barbell'),
  ('leg_shoulders_feet_elevated_hip_raise', 'Shoulders-and-Feet-Elevated Hip Raise', 'Legs', ARRAY['Gluteus Maximus', 'Hamstrings']::TEXT[], 'Calisthenics', 'Intermediate', 'Hip Extension', 'Benches / Boxes'),
  ('leg_ring_hamstring_curls', 'Gymnastic Ring Hamstring Curls', 'Legs', ARRAY['Hamstrings', 'Glutes', 'Calves']::TEXT[], 'Calisthenics', 'Advanced', 'Knee Flexion', 'Gymnastic Rings'),
  ('leg_reverse_leg_extension', 'Reverse Leg Extension', 'Legs', ARRAY['Quadriceps / Hip Flexors']::TEXT[], 'Calisthenics', 'Intermediate', 'Knee Extension', 'Bodyweight'),
  ('leg_donkey_kicks', 'Donkey Kicks', 'Legs', ARRAY['Gluteus Maximus', 'Hamstrings']::TEXT[], 'Calisthenics', 'Beginner', 'Hip Extension', 'Bodyweight'),
  ('leg_curl_machine', 'Leg Curl Machine (Lying / Seated)', 'Legs', ARRAY['Hamstrings']::TEXT[], 'Cables & Machines', 'Beginner', 'Isolation Knee Flexion', 'Machine'),
  ('leg_lunges_static_fwd_rev', 'Lunges (Static / Forward / Reverse)', 'Legs', ARRAY['Quadriceps', 'Glutes', 'Hamstrings', 'Calves']::TEXT[], 'Free Weights', 'Beginner', 'Lunge', 'Bodyweight / Dumbbells'),
  ('leg_stride_lunge', 'Stride Lunge', 'Legs', ARRAY['Hip Flexors', 'Glutes', 'Adductors']::TEXT[], 'Calisthenics', 'Intermediate', 'Lunge / Mobility', 'Bodyweight'),
  ('leg_rocket_lunge', 'Rocket Lunge', 'Legs', ARRAY['Quadriceps', 'Glutes', 'Calves']::TEXT[], 'Calisthenics', 'Explosive', 'Plyometric Lunge', 'Bodyweight'),
  ('leg_lateral_cossack_lunge', 'Lateral / Cossack Lunge', 'Legs', ARRAY['Adductors', 'Glutes', 'Quadriceps', 'Ankles']::TEXT[], 'Calisthenics', 'Intermediate', 'Lateral Squat', 'Bodyweight'),
  ('leg_calf_raises', 'Standing Floor Calf Raise (Double / Single-Leg)', 'Calves', ARRAY['Gastrocnemius', 'Soleus']::TEXT[], 'Calisthenics', 'Beginner', 'Plantarflexion', 'Bodyweight / Step'),
  ('leg_seated_calf_raise_machine', 'Seated Calf Raise Machine', 'Calves', ARRAY['Soleus']::TEXT[], 'Cables & Machines', 'Beginner', 'Plantarflexion', 'Machine'),
  ('leg_squat_calf_raise', 'Squatted Calf Raise', 'Calves', ARRAY['Soleus', 'Quadriceps']::TEXT[], 'Calisthenics', 'Intermediate', 'Plantarflexion / Isometric Squat', 'Bodyweight'),
  ('leg_stiff_leg_ankle_hops', 'Stiff-Leg Ankle Hops', 'Calves', ARRAY['Achilles Tendon', 'Plantar Fascia']::TEXT[], 'Calisthenics', 'Explosive', 'Plyometric Elasticity', 'Bodyweight'),
  ('leg_jump_rope', 'Jump Rope', 'Calves', ARRAY['Forearms', 'Cardiovascular', 'Shoulders']::TEXT[], 'Calisthenics', 'Conditioning', 'Rhythmic Elasticity', 'Jump Rope'),
  ('fb_kb_swing_variations', 'Kettlebell Swing (Russian / American / Deadstop)', 'Full Body', ARRAY['Hamstrings', 'Glutes', 'Lats', 'Core', 'Shoulders']::TEXT[], 'Free Weights', 'Intermediate', 'Ballistic Hip Hinge', 'Kettlebell'),
  ('fb_kb_swing_clean', 'Kettlebell Swing Clean', 'Full Body', ARRAY['Hamstrings', 'Glutes', 'Upper Back', 'Biceps', 'Forearms']::TEXT[], 'Free Weights', 'Intermediate', 'Ballistic Clean', 'Kettlebell'),
  ('fb_kb_half_snatch', 'Kettlebell Half Snatch', 'Full Body', ARRAY['Posterior Chain', 'Deltoids', 'Core', 'Grip']::TEXT[], 'Free Weights', 'Advanced', 'Ballistic Snatch', 'Kettlebell'),
  ('fb_kb_dead_squat', 'Kettlebell Dead Squat', 'Full Body', ARRAY['Quadriceps', 'Glutes', 'Back']::TEXT[], 'Free Weights', 'Intermediate', 'Dead-Stop Squat', 'Kettlebell'),
  ('fb_kb_thrust_jerk', 'Kettlebell Thrust Jerk', 'Full Body', ARRAY['Quadriceps', 'Deltoids', 'Triceps', 'Core']::TEXT[], 'Free Weights', 'Advanced', 'Explosive Jerk', 'Kettlebell'),
  ('fb_kb_thruster', 'Kettlebell Thruster', 'Full Body', ARRAY['Quadriceps', 'Glutes', 'Deltoids', 'Triceps', 'Core']::TEXT[], 'Free Weights', 'Advanced', 'Compound Thruster', 'Kettlebells'),
  ('fb_turkish_squad_up', 'Turkish Squad-Up / Turkish Get-Up', 'Full Body', ARRAY['Shoulder Stabilizers', 'Core', 'Glutes', 'Hips']::TEXT[], 'Free Weights', 'Advanced', 'Multi-Plane Transitional Strength', 'Kettlebell'),
  ('fb_suitcase_walk', 'Suitcase Walk', 'Full Body', ARRAY['Obliques', 'Forearms / Grip', 'Trapezius', 'Hips']::TEXT[], 'Free Weights', 'Intermediate', 'Loaded Carry / Anti-Lateral Flexion', 'Kettlebell / Dumbbell'),
  ('fb_rack_walk', 'Rack Walk', 'Full Body', ARRAY['Anterior Core', 'Upper Back', 'Trapezius', 'Quads']::TEXT[], 'Free Weights', 'Intermediate', 'Loaded Carry / Anti-Extension', 'Kettlebells'),
  ('fb_waiters_walk', 'Waiter''s Walk', 'Full Body', ARRAY['Rotator Cuff', 'Deltoids', 'Core', 'Trapezius']::TEXT[], 'Free Weights', 'Advanced', 'Overhead Loaded Carry', 'Kettlebell / Dumbbell'),
  ('fb_bear_crawl', 'Bear Crawl', 'Full Body', ARRAY['Core', 'Quadriceps', 'Deltoids', 'Serratus Anterior']::TEXT[], 'Calisthenics', 'Intermediate', 'Locomotion / Crawl', 'Bodyweight'),
  ('fb_crab_walk', 'Crab Walk', 'Full Body', ARRAY['Triceps', 'Hamstrings', 'Glutes', 'Shoulders']::TEXT[], 'Calisthenics', 'Beginner', 'Locomotion / Crawl', 'Bodyweight'),
  ('fb_crocodile_crawl', 'Crocodile Crawl', 'Full Body', ARRAY['Chest', 'Core', 'Hips', 'Shoulders']::TEXT[], 'Calisthenics', 'Advanced', 'Locomotion / Crawl', 'Bodyweight'),
  ('fb_inchworm', 'Inchworm', 'Full Body', ARRAY['Hamstrings', 'Core', 'Shoulders', 'Calves']::TEXT[], 'Calisthenics', 'Beginner', 'Dynamic Mobility Crawl', 'Bodyweight'),
  ('fb_farmers_march', 'Farmer''s March', 'Full Body', ARRAY['Forearms', 'Trapezius', 'Core', 'Hip Flexors']::TEXT[], 'Free Weights', 'Intermediate', 'Loaded March', 'Dumbbells / Kettlebells'),
  ('fb_muscle_up', 'Muscle-Up (Bar / Rings)', 'Full Body', ARRAY['Lats', 'Chest', 'Triceps', 'Biceps', 'Core']::TEXT[], 'Calisthenics', 'Advanced', 'Explosive Transition', 'Pull-Up Bar / Rings'),
  ('fb_burpees', 'Standard Burpee / Chest-to-Floor Burpee', 'Full Body', ARRAY['Chest', 'Quads', 'Core', 'Cardiovascular']::TEXT[], 'Calisthenics', 'Conditioning', 'Full Body Plyometric', 'Bodyweight'),
  ('fb_mountain_climbers', 'Mountain Climbers', 'Full Body', ARRAY['Core', 'Hip Flexors', 'Shoulders']::TEXT[], 'Calisthenics', 'Conditioning', 'Dynamic Core Locomotion', 'Bodyweight'),
  ('fb_tuck_jumps', 'Tuck Jumps', 'Full Body', ARRAY['Quads', 'Calves', 'Hip Flexors', 'Core']::TEXT[], 'Calisthenics', 'Explosive', 'Plyometric Jump', 'Bodyweight'),
  ('fb_jumping_jacks', 'Jumping Jacks', 'Full Body', ARRAY['Calves', 'Deltoids', 'Cardiovascular']::TEXT[], 'Calisthenics', 'Conditioning', 'Aerobic Plyometric', 'Bodyweight'),
  ('fb_floor_swimmers', 'Floor Swimmers', 'Full Body', ARRAY['Erector Spinae', 'Glutes', 'Rear Deltoid', 'Hamstrings']::TEXT[], 'Calisthenics', 'Beginner', 'Posterior Kinetic Chain', 'Bodyweight'),
  ('forearm_palms_up_wrist_curl', 'Palms-Up Wrist Curl', 'Forearms', ARRAY['Grip', 'Wrist Flexors']::TEXT[], 'Free Weights', 'Beginner', 'Isolation', 'Dumbbells'),
  ('forearm_palms_down_wrist_curl', 'Palms-Down Wrist Curl', 'Forearms', ARRAY['Wrist Extensors', 'Grip']::TEXT[], 'Free Weights', 'Beginner', 'Isolation', 'Dumbbells'),
  ('forearm_grip_crush_db', 'Grip Crush', 'Forearms', ARRAY['Grip', 'Hands']::TEXT[], 'Free Weights', 'Intermediate', 'Isometric', 'Dumbbells'),
  ('core_farmers_walk', 'Farmer''s Walk', 'Full Body', ARRAY['Forearms', 'Grip', 'Traps', 'Core']::TEXT[], 'Free Weights', 'Beginner', 'Compound', 'Dumbbells / Heavy Bags'),
  ('arm_behind_back_cable_curl', 'Behind-the-Back Cable Curl', 'Biceps', ARRAY['Brachialis', 'Forearms']::TEXT[], 'Cables & Machines', 'Intermediate', 'Isolation', 'Cable Machine'),
  ('back_towel_cable_row', 'Towel Cable Row', 'Back', ARRAY['Forearms', 'Grip', 'Biceps', 'Lats']::TEXT[], 'Cables & Machines', 'Intermediate', 'Pull', 'Cable Machine + Towel'),
  ('forearm_cable_pull', 'Forearm Pull', 'Forearms', ARRAY['Grip', 'Wrists']::TEXT[], 'Cables & Machines', 'Intermediate', 'Isolation', 'Cable Pulley Machine'),
  ('forearm_squeeze_grippers', 'Forearm Squeeze', 'Forearms', ARRAY['Grip', 'Hands']::TEXT[], 'Free Weights', 'Beginner', 'Isometric', 'Hand Grippers'),
  ('chest_fingertip_pushups', 'Fingertip Pushups', 'Chest', ARRAY['Forearms', 'Fingers', 'Triceps', 'Core']::TEXT[], 'Calisthenics', 'Advanced', 'Push', 'Bodyweight'),
  ('forearm_db_wrist_curl', 'Wrist Curl (Dumbbells)', 'Forearms', ARRAY['Wrist Flexors', 'Grip']::TEXT[], 'Free Weights', 'Beginner', 'Isolation', 'Dumbbells'),
  ('forearm_db_reverse_wrist_curl', 'Reverse Wrist Curl (Dumbbells)', 'Forearms', ARRAY['Wrist Extensors', 'Grip']::TEXT[], 'Free Weights', 'Beginner', 'Isolation', 'Dumbbells'),
  ('forearm_wrist_roller', 'Wrist Roller', 'Forearms', ARRAY['Grip', 'Flexors', 'Extensors']::TEXT[], 'Free Weights', 'Intermediate', 'Isolation', 'Wrist Roller Device + Weight Plate'),
  ('neck_flexion_weighted', 'Neck Flexion (Weighted)', 'Neck', ARRAY['Sternocleidomastoid', 'Scalenes']::TEXT[], 'Free Weights', 'Intermediate', 'Isolation', 'Weight Plate + Flat Bench'),
  ('neck_extension_weighted', 'Neck Extension (Weighted)', 'Neck', ARRAY['Trapezius', 'Splenius Capitis']::TEXT[], 'Free Weights', 'Intermediate', 'Isolation', 'Weight Plate + Flat Bench'),
  ('neck_lateral_flexion', 'Lateral Neck Flexion', 'Neck', ARRAY['Lateral Cervical', 'Scalenes']::TEXT[], 'Calisthenics', 'Beginner', 'Isolation', 'Bodyweight / Flat Bench'),
  ('arm_tricep_pushdown_cable', 'Tricep Pushdown', 'Triceps', ARRAY['Anconeus']::TEXT[], 'Cables & Machines', 'Beginner', 'Isolation', 'Cable Machine'),
  ('arm_skull_crushers_ez_bb', 'Skull Crusher', 'Triceps', ARRAY['Anconeus']::TEXT[], 'Free Weights', 'Intermediate', 'Isolation', 'EZ-Bar + Bench'),
  ('back_dead_hangs', 'Dead Hangs', 'Back', ARRAY['Grip', 'Forearms', 'Shoulders', 'Lats']::TEXT[], 'Calisthenics', 'Beginner', 'Isometric', 'Pull-Up Bar'),
  ('core_plank_shoulder_taps', 'Plank with Shoulder Taps', 'Core', ARRAY['Shoulders', 'Abs', 'Obliques']::TEXT[], 'Calisthenics', 'Beginner', 'Isometric', 'Bodyweight')
ON CONFLICT (id) DO NOTHING;
